# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/opt/hostedtoolcache/go/1.13.5/x64' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path

steps:
- task: GoTool@0
  displayName: "Install Go 1.13.5"
  inputs:
    version: '1.13.5'
- task: Go@0
  displayName: "Build"
  inputs:
    command: 'build'
    arguments: 'pkg/cmd/main.go'
- task: CmdLine@2
  displayName: "Unit Test"
  inputs:
    script: |
      which go
      go get -u github.com/jstemmer/go-junit-report
      go test -v ./...
      go test -v ./... 2>&1 | $GOPATH/bin/go-junit-report > report.xml
      cat report.xml

- task: PublishTestResults@2
  displayName: "Publish Test Report"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/report.xml'

- task: CmdLine@2
  displayName: "Cross Platform Build"
  inputs:
    script: |
      /bin/bash ./script/build_platform_ci.sh
      cp **/*.tgz $(Build.ArtifactStagingDirectory)
      cp **/*.zip $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


